# Dataset & output
dataset: aptos2019
output_dir: "{OUTPUT_DIR}"

# Training hyperparameters
epochs: 50
batch_size: 32
lr: 1e-4                    # Base learning rate for pretrained layers
dropout: 0.5
early_stop_patience: 7

# Gradual unfreezing schedule (epoch: layers to unfreeze)
unfreeze_schedule:
  4: ["layer3"]
  9: ["layer4"]
  19: ["layer2"]
  29: ["layer1"]

# Misc
seed: 42
num_workers: 8