# Dataset & output
dataset: aptos2019
output_dir: "{OUTPUT_DIR}"

# Training hyperparameters
epochs: 30
warmup_epochs: 5   
batch_size: 32
lr: 1e-4
warmup_lr: 1e-3              
dropout: 0.5
early_stop_patience: 9

# Misc
seed: 42
num_workers: 8