# Dataset & output
dataset: aptos2019
output_dir: "{OUTPUT_DIR}"

# Training hyperparameters
epochs: 50
batch_size: 32
lr: 1e-5                    
dropout: 0.3
early_stop_patience: 7
loss: "ce"

# Gradual unfreezing schedule (epoch: layers to unfreeze)
unfreeze_schedule:
  0: ["fc"]        # train head from the start
  5: ["layer4"]    # last ResNet block
  10: ["layer3"]   # mid-level features
  20: ["layer2"]   # earlier features
  30: ["layer1"]   # shallow conv block
  40: ["conv1"]    # very early conv

# Misc
seed: 42
num_workers: 8