# Dataset & output
dataset: aptos2019
output_dir: "{OUTPUT_DIR}"

# Training hyperparameters
epochs: 50
batch_size: 32
lr: 1e-5                    
dropout: 0.5
early_stop_patience: 7

# Gradual unfreezing schedule (epoch: layers to unfreeze)
unfreeze_schedule:
  0: ["fc"]
  2: ["layer4"]
  4: ["layer3"]
  6: ["layer2"]
  8: ["layer1"]
  10: ["conv1"]

# Misc
seed: 42
num_workers: 8